services:
  # Backend API Service
  - type: web
    name: sof-extractor-backend
    env: python
    region: ohio  # Choose your preferred region
    plan: free  # Or choose a paid plan if needed
    buildCommand: |
      cd backend &&
      pip install --upgrade pip &&
      pip install -r requirements.txt
    startCommand: cd backend && gunicorn -k uvicorn.workers.UvicornWorker app:app --bind 0.0.0.0:$PORT
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1  # Adjust size as needed
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: CORS_ORIGINS
        value: "https://sof-extractor-frontend.onrender.com"
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 1440
      - key: UPLOAD_DIR
        value: /data/uploads
      - key: RESULTS_DIR
        value: /data/results

  # Frontend Static Site
  - type: static
    name: sof-extractor-frontend
    region: ohio  # Choose your preferred region
    buildCommand: |
      cd frontend &&
      npm install &&
      npm run build
    staticPublishPath: ./frontend/build
    pullRequestPreviewsEnabled: true
    autoDeploy: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: sof-extractor-backend
          envVarKey: RENDER_EXTERNAL_URL  # This will use the full URL for the backend service
      - key: REACT_APP_BACKEND_URL
        fromService:
          type: web
          name: sof-extractor-backend
          envVarKey: RENDER_EXTERNAL_URL
